name: Build and Deploy

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: pnpm

      - run: pnpm install --recursive

      - run: mkdir --parents page

      - run: pnpm copy

      - uses: actions/upload-artifact@v4
        with:
          name: pages
          path: page/

  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: pages
          path: page/

      - uses: actions/upload-pages-artifact@v3
        with:
          path: page/

  deploy:
    runs-on: ubuntu-latest
    needs: upload

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
